import os, time, json

APP_DIR = "generated_apps"
REGISTRY = "data/apps.json"

def _load():
    try:
        return json.load(open(REGISTRY,"r",encoding="utf-8"))
    except:
        return []

def _save(data):
    os.makedirs("data", exist_ok=True)
    json.dump(data, open(REGISTRY,"w",encoding="utf-8"), ensure_ascii=False, indent=2)

def list_apps():
    return _load()

def make_web_app(name, title=None, body=None):
    safe = "".join(c for c in name if c.isalnum() or c in "-_") or f"app_{int(time.time())}"
    title = title or safe
    body = body or "Web app generated by ΝΟΥΣ AI OS"

    path = os.path.join(APP_DIR, safe)
    os.makedirs(path, exist_ok=True)

    html = f"""<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
body{{font-family:Arial;background:#111;color:white;padding:20px}}
.card{{background:#1e1e1e;border-radius:16px;padding:20px}}
button{{padding:12px;border:0;border-radius:10px;background:#00ff88}}
</style>
</head>
<body>
<div class="card">
<h1>{title}</h1>
<p>{body}</p>
<button onclick="alert('ΝΟΥΣ app active')">OK</button>
</div>
</body>
</html>"""

    open(os.path.join(path, "index.html"), "w", encoding="utf-8").write(html)

    apps = _load()
    apps = [a for a in apps if a.get("name") != safe]
    apps.append({
        "name": safe,
        "title": title,
        "path": path,
        "url": f"/apps/{safe}/",
        "created": int(time.time())
    })
    _save(apps)

    return {"created": True, "name": safe, "path": path, "url": f"/apps/{safe}/"}
